# Guia de Introdução ao NumPy

NumPy, que significa Numerical Python, é uma biblioteca fundamental para a computação científica em Python. Ela fornece suporte para arrays e matrizes, além de funções matemáticas para operações com esses objetos. É, também, a base da biblioteca Pandas.



## Filtros e np.where()

A função `np.where()` é muito útil para fazer uma seleção condicional de elementos de um array. Por exemplo, em uma empresa, você pode querer identificar quais funcionários têm salários acima da média.


In [2]:
import numpy as np

# Salários dos funcionários
salarios = np.array([3000, 3500, 4000, 2000, 4500, 4000, 5000])

# Calcular a média salarial
media = np.mean(salarios)
print(media)


3714.285714285714


In [3]:
# Identificar funcionários com salários acima da média
indice_funcionarios_acima = np.where(salarios > media)
print(indice_funcionarios_acima)


(array([2, 4, 5, 6], dtype=int64),)


In [4]:
# dar bônus de 10% para os funcionários com salários abaixo da média
salarios_ajustados1 = np.where(salarios < media, salarios * 1.1, salarios)
print(salarios)
print(salarios_ajustados1)

[3000 3500 4000 2000 4500 4000 5000]
[3300. 3850. 4000. 2200. 4500. 4000. 5000.]


In [6]:
# filtrar os salários entre 3000 e 4500 com where
indice_salarios_dentro_3000_4500 = np.where((salarios_ajustados1 >= 3000) & (salarios_ajustados1 <= 4500))
print(indice_salarios_dentro_3000_4500)


(array([0, 1, 2, 4, 5], dtype=int64),)


In [7]:
# filtrar os salários abaixo de 3000 ou acima de 4500 com where
indice_salarios_fora_3000_4500 = np.where((salarios_ajustados1 < 3000) | (salarios_ajustados1 > 4500))
print(indice_salarios_fora_3000_4500)

(array([3, 6], dtype=int64),)


In [9]:
# Realizar operações com os indices
# Primeiro caso - aumento de 5%
# Segundo caso - aumento de 10%
salarios_ajustados2 = np.where((salarios_ajustados1 >= 3000) & (salarios_ajustados1 <= 4500), salarios_ajustados1 * 1.05, salarios_ajustados1 * 1.1)
print(salarios_ajustados2)


[3465.  4042.5 4200.  2420.  4725.  4200.  5500. ]
