## Exercício

Você é um engenheiro de produção e tem os tempos de ciclo (em minutos) de uma linha de produção em um array NumPy. Seu trabalho é identificar quaisquer tempos de ciclo que estão dois desvios padrão acima ou abaixo da média. Use o seguinte array para sua análise: `tempos_ciclo = np.array([5.5, 5.7, 5.9, 6.0, 5.8, 5.6, 5.7, 7.2, 4.8])`. 

In [5]:
import numpy as np

tempos_ciclo = np.array([5.5, 5.7, 5.9, 6.0, 5.8, 5.6, 5.7, 7.2, 4.8])
media = np.mean(tempos_ciclo) 
desvio_padrao = np.std(tempos_ciclo)
print(media)
print(desvio_padrao)

5.8
0.592546294487706


In [7]:
# Aplicando a condição
condicao1 = (tempos_ciclo < media - 2 * desvio_padrao) | (tempos_ciclo > media + 2 * desvio_padrao)
indices_condicao1 = np.where(condicao1)
print(tempos_ciclo[indices_condicao1])
print(f'As anomalias detectadas pela primeira condição são {tempos_ciclo[indices_condicao1]}')

[7.2]
As anomalias detectadas pela primeira condição são [7.2]


#### Bônus 1

In [10]:
print(condicao1)
condicao2 = ~condicao1
print(condicao2)

indices_condicao2 = np.where(~condicao1)
print(tempos_ciclo[indices_condicao2])
print(f'OS dados que não são anomalias pela primeira condição são {tempos_ciclo[indices_condicao2]}')

[False False False False False False False  True False]
[ True  True  True  True  True  True  True False  True]
[5.5 5.7 5.9 6.  5.8 5.6 5.7 4.8]
OS dados que não são anomalias pela primeira condição são [5.5 5.7 5.9 6.  5.8 5.6 5.7 4.8]


#### Bônus 2

In [23]:
# Gerando dados aleatórios numa distribuição Gaussiana(Normal)
rng = np.random.default_rng()

tempos_ciclo_gerados = rng.normal(loc= media, scale= desvio_padrao, size= 100)
print(tempos_ciclo_gerados)


[6.09140344 5.71607043 5.23750434 5.61154993 5.32859761 5.7514832
 5.43052982 5.03212551 6.03227788 6.02342465 5.56340076 5.49763428
 5.30710909 5.89805905 5.80340926 5.31351477 4.88039116 5.31962014
 5.67000317 6.70526852 6.04199614 6.6099226  6.28525167 5.39238187
 6.15215628 5.52643565 5.56829946 5.16529462 6.5931184  6.53165751
 4.67486826 5.89890774 6.17236266 5.71606765 6.4519287  5.68208788
 6.67108116 6.02978847 5.64609985 5.36930225 6.75704618 6.18625316
 5.70697833 7.13332975 5.70809463 5.11299529 4.61459397 6.73158215
 4.60041536 5.23426453 4.01417458 6.09381819 5.84639458 6.32502784
 6.86539565 5.97477087 5.48113147 6.16479693 5.88554327 5.05616223
 6.18164933 5.81700473 6.61843268 5.48536423 5.86448945 6.49999496
 5.34392519 5.75342682 5.09817324 5.28729072 5.7295283  6.39271991
 6.00877583 6.57510209 4.97749775 6.29417868 6.15028599 6.56507962
 5.29488487 6.03899783 5.90120173 5.85042919 6.72581843 5.34411415
 5.36221706 6.40170865 5.73361804 6.40218176 5.60742149 6.51183

In [24]:
print(np.mean(tempos_ciclo_gerados))
print(np.std(tempos_ciclo_gerados))


5.817243074095976
0.595852193693319


In [25]:
# Reaplicando a Condição 1
nova_condicao1 = (tempos_ciclo_gerados < media - 2 * desvio_padrao) | (tempos_ciclo_gerados > media + 2 * desvio_padrao)
indices_nova_condicao1 = np.where(nova_condicao1)
print(indices_nova_condicao1)
print(tempos_ciclo_gerados[indices_nova_condicao1])
print(f'Foram detectadas nos dados as seguintes anomalias: { tempos_ciclo_gerados[indices_nova_condicao1]}')

(array([43, 46, 48, 50], dtype=int64),)
[7.13332975 4.61459397 4.60041536 4.01417458]
Foram detectadas nos dados as seguintes anomalias: [7.13332975 4.61459397 4.60041536 4.01417458]
