## Exercício

Você é um gerente de vendas e tem os dados de vendas de três produtos diferentes (Produto A, Produto B, Produto C) para os últimos 5 dias em um array 2D NumPy. Cada linha do array representa um produto e cada coluna representa um dia. Seu trabalho é calcular as vendas totais para cada produto e para cada dia.

Use o seguinte array para sua análise:

```python
vendas = np.array([[50, 60, 70, 65, 80],[85, 90, 78, 92, 88],[72, 75, 68, 77, 76]])
```

**Solução:**


In [2]:
import numpy as np
vendas = np.array([[50, 60, 70, 65, 80],[85, 90, 78, 92, 88],[72, 75, 68, 77, 76]])
print(vendas)

[[50 60 70 65 80]
 [85 90 78 92 88]
 [72 75 68 77 76]]


###### VENDAS TOTAIS POR PRODUTO

In [5]:
total_produto = vendas.sum(axis= 1)
print(total_produto)
print(f'Total de vendas do produto A foi {total_produto[0]}')
print(f'Total de vendas do produto B foi {total_produto[1]}')
print(f'Total de vendas do produto C foi {total_produto[2]}')

[325 433 368]
Total de vendas do produto A foi 325
Total de vendas do produto B foi 433
Total de vendas do produto C foi 368


###### VENDAS TOTAIS POR DIA

In [6]:
total_dia = np.sum(vendas, axis= 0)
print(total_dia)
for i in range(len(total_dia)):
    print(f'Total de vendas do {i+1}o. foi {total_dia[i]} ')

[207 225 216 234 244]
Total de vendas do 1o. foi 207 
Total de vendas do 2o. foi 225 
Total de vendas do 3o. foi 216 
Total de vendas do 4o. foi 234 
Total de vendas do 5o. foi 244 
